services:
  - type: web
    name: todolist
    env: ruby
    plan: free
    buildCommand: ./bin/render-build.sh
    startCommand: bundle exec puma -C config/puma.rb
    autoDeploy: true
    healthCheckPath: /up
    envVars:
      - key: RAILS_ENV
        value: production
      - key: RAILS_MASTER_KEY
        sync: false
      - key: APP_HOST
        value: your-app.onrender.com
      - key: RAILS_LOG_TO_STDOUT
        value: "1"
      - key: DATABASE_URL
        fromDatabase:
          name: todolist-db
          property: connectionString

databases:
  - name: todolist-db
    plan: free